notifications:
  email: false
sudo: false
language: java
jdk:
  - oraclejdk8
install:
  - mvn install -s ~/travis_maven.xml -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
  - mvn test -B -s ~/travis_maven.xml
after_success:
  - mvn clean cobertura:cobertura coveralls:report
