version: "2"

services:
#Mongo and Swift are not Dockerized yet
  relational-database:
    build:
      context: ./postgresql
    image: api-postgresql-database
    ports:
    - "5432:5432"
    environment:
    #postgres super user
        POSTGRES_PASSWORD: postgres
        POSTGRES_USER: postgres
    restart: always

  graph-database:
    build:
      context: ./neo4j
    image: api-neo4j-database
    ports:
      - "7474:7474"
      - "5005:5005"
    restart: always

  appserver:
    build:
      context: ./tomcat
    image: api-tomcat-server
#    environment:
#      CATALINA_OPTS: -Xms512M -Xmx4096M -server -XX:+UseParallelGC
    # mount point for application in tomcat
    volumes:
      - ../api2-war/target/api:/tomcat/webapps/api
    links:
      - graph-database:api-neo4j-database
      - relational-database:api-postgresql-database
    # open ports for tomcat and remote debugging
    ports:
      - "8080:8080"
      - "8000:8000"
    restart: always
    depends_on:
      - relational-database

  webserver:
    build:
      context: ./apache
    image: api-webserver
    links:
          - appserver:api-tomcat-server
    ports:
      - "80:80"
    restart: always
    environment:
      WWW_HOST: www.myeuropeana.eu
      ANNOTATIONS_HOST: test-annotations.europeana.eu
      API_HOST: appserver:8080
      EXHIBITIONS_HOST: exhibitions-test.cfapps.io
      PORTAL_HOST: portal-test.cfapps.io

