#api2.url.host=http://gamma-api.de.a9sapp.eu
#api2.url.oauth.token=http://gamma-api.de.a9sapp.eu/oauth/authorize
#api2.url.oauth.authorize=http://gamma-api.de.a9sapp.eu/oauth/token



api2:
  key: api2demo
  secret: verysecret
  url:
    host: http://localhost:8080
    oauth:
      token: ${api2.url.host}/oauth/token
      authorize: ${api2.url.host}/oauth/authorize

logging:
  level:
    org.springframework.web=DEBUG

spring:
  application:
    name: API2 oAuth2 Demo
  velocity:
    enabled: false

server:
  port: 8081